title: Alpha Software
company_name: Công&nbsp;ty TNHH Phát&nbsp;triển Phần&nbsp;mềm Alpha
email: tuananh@alphasoftwaregroup.com
description: >- # TODO: Revise description
  Hợp tác cùng Alpha Software để xây dựng hệ thống quản lý quy trình dệt may.
  Giải pháp chuyển đổi số của Alpha Software sẽ mang lại hiệu suất vượt bậc cho
  những doanh nghiệp có mong muốn dẫn đầu trong lĩnh vực dệt may.
# baseurl: # the subpath of your site, e.g. /blog
url: https://www.alphasoftwaregroup.com # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed