title: "Alpha Software: Chuyển đổi số nhà máy dệt may"
company_name: Công ty TNHH Phát triển Phần mềm Alpha
email: alphasoftware102@gmail.com
description: Giải pháp phần mềm quản lý nhà máy dệt may hàng đầu. Tối ưu hiệu suất, nâng tầm doanh nghiệp, khẳng định vị thế dẫn đầu trong ngành dệt may.
url: https://www.alphasoftwaregroup.com/
facebook_page: https://www.facebook.com/profile.php?id=100070371223404

# Build settings
markdown: kramdown

exclude:
  - node_modules/
  - docs/
  - update-class-names.js
  - _classMap.json
  - package-lock.json
  - package.json
  - postcss.config.js
  - .gititnore
  - Gemfile
  - Gemfile.lock
